SRCS    =       main.c  \
                        ft_putchar.c    \
                        ft_putstr.c     \
                        ft_strcmp.c     \
                        ft_strdup.c     \
                        ft_translate.c  \
                        ft_rev_int_tab.c        \
                        split.c         \
			test.c		\

NAME    = rush-02

${NAME}:
			gcc  -Wall -Wextra -Werror ${SRCS} -o ${NAME}

all :		${NAME}

clean :
			rm -f ${NAME}

